[package]
name = "ddsd"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bcdec_rs = "0.1.2"
bitflags = "2.4.0"
bytemuck = "1.20.0"

[dev-dependencies]
glob = "0.3.1"
