[package]
name = "ddsd"
version = "0.1.0"
license = "MIT OR Apache-2.0"

description = "DDS decoding library in pure safe Rust"
categories = ["multimedia::images"]
authors = ["Michael Schmidt"]
repository = "https://github.com/RunDevelopment/ddsd"

edition = "2021"
rust-version = "1.61"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "2.4.0"
zerocopy = "0.8.14"

[dev-dependencies]
glob = "0.3.1"
png = "0.17"
